/* Self-host the web fonts, subset to the scripts we actually render.
     node scripts/build-fonts.mjs
   Google's css2 response is ~469KB because Shippori Mincho ships ~480
   unicode-range blocks for Japanese, which this site never renders — it is used
   only for numerals. We keep latin/latin-ext for every family, plus arabic for
   Amiri, download those woff2 files into src/fonts/, and emit src/css/fonts.css.
   That removes two third-party origins from the critical path. */
import fs from 'node:fs';
import path from 'node:path';

const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";
const CSS_URL = "https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,400;0,500;0,600;1,400;1,500;1,600&family=Libre+Baskerville:ital,wght@0,400;0,700;1,400&family=Shippori+Mincho:wght@400;500;600;700&family=Amiri:ital,wght@0,400;0,700;1,400&display=swap";
// which subsets each family may keep
const KEEP = {
  "Cormorant Garamond": ["latin", "latin-ext"],
  "Libre Baskerville": ["latin", "latin-ext"],
  "Amiri": ["latin", "latin-ext", "arabic"],
  "Shippori Mincho": ["latin"]      // numerals only
};

const css = await (await fetch(CSS_URL, { headers: { "user-agent": UA } })).text();
fs.mkdirSync("src/fonts", { recursive: true });
fs.mkdirSync("src/css", { recursive: true });

const blocks = css.split("@font-face").slice(1);
let out = ["/* Self-hosted subset of the site's web fonts — generated by scripts/build-fonts.mjs.",
           "   Subsets: latin + latin-ext for all families, arabic for Amiri, latin only for",
           "   Shippori Mincho (used for numerals). Do not edit by hand. */"].join("\n") + "\n";
let kept = 0, skipped = 0, bytes = 0;
const seen = new Set();

for (const b of blocks) {
  const fam = (b.match(/font-family:\s*'([^']+)'/) || [])[1];
  const sub = (b.match(/\/\*\s*([a-z0-9-]+)\s*\*\//) || [])[1];
  const style = (b.match(/font-style:\s*([a-z]+)/) || [])[1] || "normal";
  const weight = (b.match(/font-weight:\s*([0-9]+)/) || [])[1] || "400";
  const url = (b.match(/url\((https:[^)]+\.woff2)\)/) || [])[1];
  const range = (b.match(/unicode-range:\s*([^;]+);/) || [])[1];
  if (!fam || !url || !sub) { skipped++; continue; }
  if (!(KEEP[fam] || []).includes(sub)) { skipped++; continue; }

  const file = (fam.toLowerCase().replace(/[^a-z]+/g, "-") + "-" + weight + "-" + style + "-" + sub + ".woff2");
  if (!seen.has(file)) {
    const buf = Buffer.from(await (await fetch(url, { headers: { "user-agent": UA } })).arrayBuffer());
    fs.writeFileSync(path.join("src/fonts", file), buf);
    bytes += buf.length; seen.add(file);
  }
  out += `@font-face{font-family:'${fam}';font-style:${style};font-weight:${weight};font-display:swap;` +
         `src:url('../fonts/${file}') format('woff2');` + (range ? `unicode-range:${range};` : "") + `}\n`;
  kept++;
}
fs.writeFileSync("src/css/fonts.css", out);
console.log("kept @font-face:", kept, "| skipped:", skipped);
console.log("files:", seen.size, "| total woff2:", (bytes / 1024).toFixed(0) + "KB");
console.log("fonts.css:", (fs.statSync("src/css/fonts.css").size / 1024).toFixed(1) + "KB",
            "(was ~469KB of remote CSS)");
